services:
  - type: web
    name: calculadoragdu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 300 --workers 1 --threads 2 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
